### ISSUE TITLE
Why are the eci computed with ecomplexity different from their given values?

### ISSUE THREAD

**Issue by chengjun** [cid-harvard/py-ecomplexity#8] opened 2019-07-19 09:03 UTC
Thank you for contributing this brilliant python package. I am trying to compute the eci (`eci_ecomplexity_cal`) using the `country_sitcproduct2digit_year.csv` data. In the `country_sitcproduct2digit_year.csv` data, there are given eci values (`eci_hidalgo_rep`) . I found that they do not line up exactly. 

![image](https://user-images.githubusercontent.com/543384/61523227-8528ff80-aa46-11e9-9759-4e0453baa311.png)

Further I find that the given eci values (`eci_hidalgo_rep`) has a better correlation with the GDP per capita compared with the eci computed using this python package (`eci_ecomplexity_cal`). 

![image](https://user-images.githubusercontent.com/543384/61523390-dd600180-aa46-11e9-99df-075d88dba2b6.png)

**Comment by shreyasgm** [comment] 2019-07-19 16:45
Thanks for bringing this to our attention. We'll look into this. 

Here is code to reproduce the issue:

```python
import pandas as pd
import numpy as np
import seaborn as sns
from ecomplexity import ecomplexity

# Import trade data from CID Atlas
data_url = "https://intl-atlas-downloads.s3.amazonaws.com/country_sitcproduct2digit_year.csv.zip"
data = pd.read_csv(data_url, compression="zip", low_memory=False)
data.head()

# Calculate eci's
data = data[['year','location_code','sitc_product_code','export_value','sitc_eci']]
data = data[data.year==data.year.max()]
trade_cols = {'time':'year', 'loc':'location_code', 'prod':'sitc_product_code', 'val':'export_value'}
cdata = ecomplexity(data, trade_cols)
cdata = cdata[['location_code','eci','sitc_eci']].drop_duplicates(['location_code'])

# Compare against Atlas
sns.scatterplot('sitc_eci','eci', data=cdata)
```

**Comment by shreyasgm** [comment] 2019-07-19 19:10
Ah, this issue is much simpler than I expected. I didn't notice earlier, but you're using 2-digit SITC codes. The calculations for ECI in the Atlas are based on 4-digit SITC codes. This explains most of the discrepancy that you're seeing. Any remaining differences are due to the fact that on the Atlas, we restrict the set of countries to ones with reliable data for ECI calculations. Learn more about Atlas data [here](http://atlas.cid.harvard.edu/data)

Closing as not an issue.

**Closed by shreyasgm** 2019-07-19 19:10 UTC
Labels: question

**Comment by chengjun** [comment] 2019-07-20 08:02
Thank you for your generous and quick reply. I will try the 4-digit SITC dataset.

**Comment by chengjun** [comment] 2019-07-20 09:12
@shreyasgm 
Thank you for your generous and quick reply. I have just tried the 4-digit SITC dataset using your python script as follows:

```
import pandas as pd
import numpy as np
import seaborn as sns
from ecomplexity import ecomplexity

# Import trade data from CID Atlas
data = pd.read_csv('../data/country_partner_sitcproduct4digit_year_2017.zip', compression="zip", low_memory=False)
data.head()

# Calculate eci's
data = data[['year','location_code','sitc_product_code','export_value','sitc_eci']]
data = data[data.year==data.year.max()]
trade_cols = {'time':'year', 'loc':'location_code', 'prod':'sitc_product_code', 'val':'export_value'}
cdata = ecomplexity(data, trade_cols)
cdata = cdata[['location_code','eci','sitc_eci']].drop_duplicates(['location_code'])

# Compare against Atlas
sns.scatterplot('sitc_eci','eci', data=cdata)
```
This is the result. As you can see, they are still not the same as the given EIC. 

![image](https://user-images.githubusercontent.com/543384/61576731-0ef0cf80-ab10-11e9-904f-d9375effa071.png)

Your comments would be appreciated. Thanks a lot.

**Comment by shreyasgm** [comment] 2019-07-20 10:32
I did mention earlier that there would be some remaining differences. Atlas data uses a set of processes that clean the trade data based on bilateral reporting, and restrict the set of countries used for ECI calculations. More [here](http://atlas.cid.harvard.edu/data). If you have specific questions about the Atlas data itself, I would suggest that you request help from the Atlas team [here](http://atlas.cid.harvard.edu/data#request-help).

**Comment by chengjun** [comment] 2019-07-20 12:15
@shreyasgm  Thank you for your kindly reply. I have benefited a lot from your insightful and comprehensive answers which have well addressed my question. The idea of ECI is very inspiring and it could be applied to many other areas. Thanks again for your maintaining of this wonderful Python package. Best regards. C.J.
